from enum import Enum

class RatingType(Enum):
    ACCELERATION = "acceleration"
    AGILITY = "agility"
    JUMPING = "jumping"
    STAMINA = "stamina"
    STRENGTH = "strength"
    AWARENESS = "awareness"
    BC_VISION = "bCVision"
    BLOCK_SHEDDING = "blockShedding"
    BREAK_SACK = "breakSack"
    BREAK_TACKLE = "breakTackle"
    CARRYING = "carrying"
    CATCH_IN_TRAFFIC = "catchInTraffic"
    CATCHING = "catching"
    CHANGE_OF_DIRECTION = "changeOfDirection"
    DEEP_ROUTE_RUNNING = "deepRouteRunning"
    FINESSE_MOVES = "finesseMoves"
    HIT_POWER = "hitPower"
    IMPACT_BLOCKING = "impactBlocking"
    INJURY = "injury"
    JUKE_MOVE = "jukeMove"
    KICK_ACCURACY = "kickAccuracy"
    KICK_POWER = "kickPower"
    KICK_RETURN = "kickReturn"
    LEAD_BLOCK = "leadBlock"
    MAN_COVERAGE = "manCoverage"
    MEDIUM_ROUTE_RUNNING = "mediumRouteRunning"
    OVERALL = "overall"
    PASS_BLOCK = "passBlock"
    PASS_BLOCK_FINESSE = "passBlockFinesse"
    PASS_BLOCK_POWER = "passBlockPower"
    PLAY_ACTION = "playAction"
    PLAY_RECOGNITION = "playRecognition"
    POWER_MOVES = "powerMoves"
    PRESS = "press"
    PURSUIT = "pursuit"
    RELEASE = "release"
    RUN_BLOCK = "runBlock"
    RUN_BLOCK_FINESSE = "runBlockFinesse"
    RUN_BLOCK_POWER = "runBlockPower"
    RUNNING_STYLE = "runningStyle"
    SHORT_ROUTE_RUNNING = "shortRouteRunning"
    SPECTACULAR_CATCH = "spectacularCatch"
    SPEED = "speed"
    SPIN_MOVE = "spinMove"
    STIFF_ARM = "stiffArm"
    TACKLE = "tackle"
    THROW_ACCURACY_DEEP = "throwAccuracyDeep"
    THROW_ACCURACY_MID = "throwAccuracyMid"
    THROW_ACCURACY_SHORT = "throwAccuracyShort"
    THROW_ON_THE_RUN = "throwOnTheRun"
    THROW_POWER = "throwPower"
    THROW_UNDER_PRESSURE = "throwUnderPressure"
    TOUGHNESS = "toughness"
    TRUCKING = "trucking"
    ZONE_COVERAGE = "zoneCoverage"

class Rating:
    def __init__(self, rating_type: RatingType, rating: int):
        self.rating_type = rating_type
        self.rating = rating